MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #WEIGHT: "/media/SSD_1TB/ApolloScape/6DVNET_experiments/e2e_3d_car_101_FPN_triple_head/Feb21-04-19_n606_step/model_0010000.pth"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False

  ROI_CAR_CLS_ROT_HEAD:
    FEATURE_EXTRACTOR: "FPN2MLP2FeatureExtractor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    MLP_HEAD_DIM: 1024
    PREDICTOR: "FPNPredictor"
    NUMBER_CARS: 34
    SHARE_BOX_FEATURE_EXTRACTOR: False
    ROT_LOSS: "L1"
    CE_CAR_CLS_FINETUNE_WIGHT: [1.2, 3.74, 12.03, 5.08, 6.69, 11.7, 20.25, 0.37, 14.32, 14.24, 84.02, 14.78, 9.46,
    13.62, 1.51, 9.96, 43.84, 1.83, 4.65, 6.62, 11.54, 0.6, 6.73, 29.48, 7.82, 5.55, 12.36, 25.85, 8.63, 6.49, 4.13,
    2.6, 6.3, 10.84]
    QUATERNION_HEMISPHERE: True

  TRANS_HEAD:
    FEATURE_EXTRACTOR: "MLPFeatureExtractor"
    PREDICTOR: "MLPCONCATPredictor"
    MLP_HEAD_DIM: 100
    INPUT_DIM: 4
    OUTPUT_DIM: 3
    TRANS_LOSS: "HUBER"
    TRANS_HUBER_THRESHOLD: 2.8
    CAMERA_INTRINSIC: (2304.54786556982, 2305.875668062, 1686.23787612802, 1354.98486439791)
    TRANS_LOSS_BETA: 0.05

  MASK_ON: True
  CAR_CLS_HEAD_ON: True
  TRANS_HEAD_ON: True

DATASETS:
  TRAIN: ("Apollo_3d_car_train", "Apollo_3d_car_val")
  TEST: ("Apollo_3d_car_test",)

INPUT:
  MIN_SIZE_TRAIN: 1200
  MIN_SIZE_TRAIN_RANGE: (1200, 1600)  # (1200, 2710)  2710 is TOO BIG!
  MAX_SIZE_TRAIN: 3384
  MAX_SIZE_TEST : 3384

DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, 8000)
  MAX_ITER: 10000
  #https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14-L30
  IMS_PER_BATCH: 3
  BASE_LR:   0.0025
  CHECKPOINT_PERIOD : 1000
