MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #WEIGHT: "/media/SSD_1TB/PASCAL3D+_release1.1/6DVNET_experiments/e2e_3d_car_101_FPN_triple_head/Mar20-00-11_n606_step/model_0092000.pth"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    MASK_LOSS_BETA: 0.1

  ROI_CAR_CLS_ROT_HEAD:
    FEATURE_EXTRACTOR: "FPN2MLP2FeatureExtractor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    MLP_HEAD_DIM: 1024
    PREDICTOR: "FPNPredictor"
    NUMBER_CARS: 34
    SHARE_BOX_FEATURE_EXTRACTOR: False
    ROT_LOSS: "L1"
    QUATERNION_HEMISPHERE: True

  TRANS_HEAD:
    FEATURE_EXTRACTOR: "MLPFeatureExtractor"
    PREDICTOR: "MLPCONCATPredictor"
    MLP_HEAD_DIM: 100
    INPUT_DIM: 4
    OUTPUT_DIM: 3
    TRANS_LOSS: "HUBER"
    TRANS_HUBER_THRESHOLD: 2.8
    CAMERA_INTRINSIC: (2304.54786556982, 2305.875668062, 1686.23787612802, 1354.98486439791)
    TRANS_LOSS_BETA: 0.05

  MASK_ON: True
  CAR_CLS_HEAD_ON: False
  TRANS_HEAD_ON: False

DATASETS:
  TRAIN: ("Pascal3d+_train",)
  TEST: ("Pascal3d+_val", )

INPUT:
  MIN_SIZE_TRAIN_RATIO: (0.8, 1.2)  # (1200, 2710)  2710 is TOO BIG!
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 2400
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST : 2400

DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 60000)
  MAX_ITER: 100000
  #https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14-L30
  IMS_PER_BATCH: 3
  BASE_LR:   0.01
  CHECKPOINT_PERIOD : 10000

TEST:
  WRITE_TO_JSON: True
  IMS_PER_BATCH : 1
  SCORE_THRESH_FOR_TRUTH_DETECTION: 0.5
